version: '3'

services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env.production

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
